### ISSUE TITLE
upi_chooser_method_channel

### ISSUE THREAD

**Issue by BLACKCAT25896** [cooltechie-info/upi-chooser#1]
StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
E/flutter ( 9535): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:322:18)
E/flutter ( 9535): <asynchronous suspension>
E/flutter ( 9535): #2      MethodChannelUpiChooser.getPlatformVersion (package:upi_chooser/upi_chooser_method_channel.dart:15:9)

**Comment by cooltechie-info** [comment]
Provide additional error logs to find out the issue!
